### ISSUE TITLE
Favicon not showing up on some web3 browsers

### ISSUE THREAD

**Issue by how-do-i-code** [Agave-DAO/agave-frontend#132]
Repro'd on Coinbase Wallet. Can someone repro on any other mobile web3 browsers?

![image](https://user-images.githubusercontent.com/72081122/146305991-92a52ad7-e880-48fd-80b1-51a1f3381fac.png)

Comparing this to Gardens UI using a favicon checker, a fix may be to include a favicon.ico in the code base. 

#### Agave
https://realfavicongenerator.net/favicon_checker?protocol=http&site=agave.finance

#### Gardens
https://realfavicongenerator.net/favicon_checker?protocol=https&site=gardens.1hive.org%2F

-Keppa

**Comment by Luigy-Lemon** [comment]
Fixed in 90116456554db8a77eadb1851e9f1e0bfbf9d0d2
