### ISSUE TITLE
On Main Deposit Page wxDai balance is shown instead of xDai

### ISSUE THREAD

**Issue by mrtdlgc** [Agave-DAO/agave-frontend#99]
On the main deposit page under balances, what I see next to my xDai balance is actually the wxDai in my wallet that I wrapped a few days ago. It shows the wxDai balance correctly as follows.
![image](https://user-images.githubusercontent.com/26493609/131747530-0a951cd0-c0db-4e07-93d5-f974ef0756f6.png)

Also, on reserve overview page, the same issue above repeats as it can be seen on the left side of the following screen:
![image](https://user-images.githubusercontent.com/26493609/131748877-4e0bb0e4-01d2-4721-b5e8-43417a2f3363.png)

However, after clicking xDai on that main deposit screen, I see the amount of xDai and not wxDai balance, which I assume is how it should have shown on the first screen as well.
![image](https://user-images.githubusercontent.com/26493609/131747580-8cec9010-64a6-4373-b0c8-2021de06e500.png)

Relevant Forum Link: https://forum.1hive.org/t/feedback-on-agave-platform/4297/6

It should be showing xDai on the main deposit page as well is what I guess.

**Comment by zedkai** [comment]
There are two possible fixes for this, depending on preference:
- Show XDAI and WXDAI as separate reserves and let the user choose either
  - Pros: Lets the user make transactions to/from either cleanly
  - Cons: Redundant relative to their wallet- but the wallet doesn't have a "deposit XDAI" button, so where do we put one?
- When a row describes the wrapped native token, show wrapped *and* unwrapped as combined values
  - Should be done chain-independently, using whatever `useWrappedNativeToken` returns
  - Pros: Lets us show a total, and offer (small text? hover tooltip?) views of the individual types present
  - Cons: Makes transacting less literal, as we now have to determine which to use and maybe how to handle "mixed" transactions

**Comment by Luigy-Lemon** [comment]
This issue has been closed with the latest merge to Production
